inherit_gem:
  rubocop-rootstrap:
    - config/rails_edge.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - db/schema.rb
    - config/initializers/pagy.rb
    - bin/bundle
    - bin/yarn

Lint/UnusedMethodArgument:
  Exclude:
    - spec/support/devise_token_auth_overrides.rb

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
    - db/migrate/20220523140253_create_delayed_jobs.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/20220523101453_devise_create_users.rb

Rails/Delegate:
  Exclude:
    - app/controllers/api/concerns/act_as_api_request.rb

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/api/v1/api_controller.rb
