default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= Rails.application.credentials.db_password %>
  # If you using docker the host should be "db"
  host: <%= ENV['DB_HOST'] %>
  port: 5432
  database: <%= ENV.fetch("APP_NAME") { "rails_template" } %>_<%= Rails.env %>

development:
  <<: *default

test:
  <<: *default


production:
  <<: *default

